### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by ConnorMarcus** [WillMarcuss/TicTacToe-with-JavaScript#2]
Here are some suggestions of small things I would change:

- [x] **Important: There should only be one pair of body tags in an html document. Also all html elements not inside the head tags should be inside the body tags.
- [x] The horizontal and vertical lines in the html document are represented by empty div elements which is fine but they can really just be the border of some other elements (though this would require restructuring some of the html and css).
- [x] You can add multiple classes to an html element (each class name is separated by a space). This way in the css you can remove duplicated lines such as "border-left: 6px solid green;" and "font-family: myFont;" and put them into a common class selector. Alternatively, if you move all elements inside the body tag, you can just select this tag and put any common styles inside this selector.

**Comment by WillMarcuss** [comment]
Oops yeah just realized the first one, and just adjusted the third, Thanks!

**Comment by WillMarcuss** [comment]
just updated and fixed all. Thx
